# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zalupa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddRecord(object):
    def setupUi(self, AddRecord):
        AddRecord.setObjectName("AddRecord")
        AddRecord.resize(500, 600)
        AddRecord.setMinimumSize(QtCore.QSize(500, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(AddRecord)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(AddRecord)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.data = QtWidgets.QTextEdit(self.frame)
        self.data.setStyleSheet("border:none;\n"
"background-color: rgba(0,0,0,0);")
        self.data.setObjectName("data")
        self.verticalLayout_2.addWidget(self.data)
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 300))
        self.textEdit.setStyleSheet("border:none;\n"
"background-color: rgba(0,0,0,0);")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit, 0, QtCore.Qt.AlignVCenter)
        self.save_button = QtWidgets.QPushButton(self.frame)
        self.save_button.setObjectName("save_button")
        self.verticalLayout_2.addWidget(self.save_button)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(AddRecord)
        QtCore.QMetaObject.connectSlotsByName(AddRecord)

    def retranslateUi(self, AddRecord):
        _translate = QtCore.QCoreApplication.translate
        AddRecord.setWindowTitle(_translate("AddRecord", "Dialog"))
        self.save_button.setText(_translate("AddRecord", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddRecord = QtWidgets.QDialog()
    ui = Ui_AddRecord()
    ui.setupUi(AddRecord)
    AddRecord.show()
    sys.exit(app.exec_())
